services:

  postgres:
    container_name: crittercommerce-postgres
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - pg_network

  sqlserver:
    container_name: crittercommerce-sqlserver
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - "1434:1433"
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=P@55w0rd"
      - "MSSQL_PID=Developer"
    networks:
      - sql_network

  rabbitmq:
    container_name: crittercommerce-rabbitmq
    image: "rabbitmq:management"
    ports:
      - "5672:5672"   # RabbitMQ Messaging Port
      - "15672:15672" # RabbitMQ Management UI
    networks:
      - rmq_network

networks:
  pg_network:
    driver: bridge
  sql_network:
    driver: bridge
  rmq_network:
    driver: bridge

volumes:
  postgres:
  sqlserver:
