@HostAddress = http://localhost:5111

GET {{HostAddress}}/api/items/
Accept: application/json

###

# curl -X 'POST'
#  'http://localhost:5111/api/items'
#  -H 'accept: application/json'
#  -H 'Content-Type: application/json'
#  -d '{
#  "name": "Bubblemonster v4"
#}'
POST {{HostAddress}}/api/items
accept: application/json
Content-Type: application/json

{
    "name": "Bubblemonster v4"
}

###

# curl -X 'GET'
#  'http://localhost:5111/api/items/0196b139-dbc1-4ec6-894a-c059ef056b8d
#  -H 'accept: application/json'
GET {{HostAddress}}/api/items/0196b139-dbc1-4ec6-894a-c059ef056b8d
Accept: application/json

###

# curl -X 'POST'
#  'http://localhost:5111/api/items/description'
#  -H 'accept: application/json'
#  -H 'Content-Type: application/json'
#  -d '{
#  "id": "0196b139-dbc1-4ec6-894a-c059ef056b8d",
#  "description": "There is now a description in the description field. Hooray! Neat. <b>Yeah.</b>"
#}'
POST http://localhost:5111/api/items/description
accept: application/json
Content-Type: application/json

{
    "id": "0196b139-dbc1-4ec6-894a-c059ef056b8d",
    "description": "There is now a description in the description field. Hooray! Neat. <b>Yeah!</b>"
}

###

# curl -X 'POST'
#  'http://localhost:5111/api/sku-reservations'
#  -H 'accept: application/json'
#  -H 'Content-Type: application/json'
#  -d '{
#  "unit": 22,
#  "username": "erik"
#}'
POST http://localhost:5111/api/sku-reservations
accept: application/json
Content-Type: application/json

{
    "unit": 22,
    "username": "erik"
}

###

# curl -X 'POST'
#  'http://localhost:5111/api/sku-reservations/unreserve'
#  -H 'accept: application/json'
#  -H 'Content-Type: application/json'
#  -d '{
#  "unit": 22,
#  "username": "erik"
#}'
POST http://localhost:5111/api/sku-reservations/unreserve
accept: application/json
Content-Type: application/json

{
    "unit": 22,
    "username": "erik"
}

###

# curl -X 'POST'
#  'http://localhost:5111/api/assign-sku-to-item'
#  -H 'accept: application/json'
#  -H 'Content-Type: application/json'
#  -d '{
#  "sku": 23,
#  "itemId": "0196b139-dbc1-4ec6-894a-c059ef056b8d"
#}'
POST http://localhost:5111/api/assign-sku-to-item
accept: application/json
Content-Type: application/json

{
    "sku": 23,
    "itemId": "0196b139-dbc1-4ec6-894a-c059ef056b8d"
}

###

