@HostAddress = http://localhost:5111

GET {{HostAddress}}/api/items/
Accept: application/json

###

# curl -X 'POST'
#  'http://localhost:5111/api/items'
#  -H 'accept: application/json'
#  -H 'Content-Type: application/json'
#  -d '{
#  "name": "Bubblemonster v4"
#}'
POST {{HostAddress}}/api/items
accept: application/json
Content-Type: application/json

{
    "name": "Bubblemonster v4"
}

###

# curl -X 'GET'
#  'http://localhost:5111/api/items/0196460a-8029-40b6-adf4-84073bc5cfb6'
#  -H 'accept: application/json'
GET {{HostAddress}}/api/items/0196460a-8029-40b6-adf4-84073bc5cfb6
Accept: application/json

###
