@HostAddress = http://localhost:5121

###

POST {{HostAddress}}/api/freight-shipments
accept: application/json
Content-Type: application/json

{
    "origin": "OmahaNeUsa",
    "destination": "AustinTxUsa"
}

> {%
    // Assuming the response contains an 'value' field
    client.global.set("FreightShipmentId", response.body.valueOf());
%}

###

GET {{HostAddress}}/api/freight-shipments/{{FreightShipmentId}}
accept: application/json

###

POST {{HostAddress}}/api/freight-shipments/{{FreightShipmentId}}/cancel
accept: */*
Content-Type: application/json

{
    "freightShipmentId": "{{FreightShipmentId}}",
    "reason": "unknown",
    "cancelledAt": "2025-07-01T01:02:03.780Z"
}

###

POST {{HostAddress}}/api/freight-shipments/{{FreightShipmentId}}/pickup
accept: */*
Content-Type: application/json

{
    "freightShipmentId": "{{FreightShipmentId}}",
    "pickedupAt": "2025-07-03T20:09:35.432Z"
}

###

