@HostAddress = http://localhost:5121
@Sku = 36606
@Facility = OmahaNeUsa
@FacilityLotId = A2-103

###

POST {{HostAddress}}/api/inventory-level
accept: application/json
Content-Type: application/json

{
    "sku": "{{Sku}}",
    "facility": "{{Facility}}",
    "facilityLotId": "{{FacilityLotId}}"
}

> {%
    client.global.set("InventoryLevelId", response.body.valueOf());
%}

###

GET {{HostAddress}}/api/inventory-level/{{InventoryLevelId}}
accept: application/json

###

GET http://localhost:5121/api/inventory-level/live-aggregate/{{InventoryLevelId}}
accept: application/json

###

POST http://localhost:5121/api/inventory-level/{{InventoryLevelId}}/adjust
accept: application/json
Content-Type: application/json

{
    "InventoryLevelId": "{{InventoryLevelId}}",
    "quantity": 22
}

###

