@HostAddress = http://localhost:5121
@Facility = OmahaNeUsa
@CreatedBy = erik
@SkuOne = 36606
@SkuTwo = 133742

###

GET {{HostAddress}}/api/receiving-shipments
accept: application/json

###
POST {{HostAddress}}/api/receiving-shipments
accept: application/json
Content-Type: application/json

{
    "shippingNumber": "ABC-123-DEF-2025",
    "facility": "{{Facility}}",
    "deliveredAt": "2025-07-22T04:11:42.162Z",
    "createdBy": "{{CreatedBy}}"
}

> {%
    client.global.set("ReceivedShipmentId", response.body.valueOf());
%}

###

GET {{HostAddress}}/api/receiving-shipments/{{ReceivedShipmentId}}
accept: application/json

### Add the first SKU (SkuOne)

POST {{HostAddress}}/api/receiving-shipments/{{ReceivedShipmentId}}/line-items/add
accept: application/json
Content-Type: application/json

{
    "sku": "{{SkuOne}}",
    "expectedQuantity": 13
}

### Add the second SKU (SkuTwo)

POST {{HostAddress}}/api/receiving-shipments/{{ReceivedShipmentId}}/line-items/add
accept: application/json
Content-Type: application/json

{
    "sku": "{{SkuTwo}}",
    "expectedQuantity": 50
}

###
