@HostAddress = http://localhost:5121
@FreightInventoryId = 0197c434-b9e8-475f-b848-89e23b434756

###

POST {{HostAddress}}/api/freight-shipments/schedule
accept: application/json
Content-Type: application/json

{
    "origin": "OmahaNeUsa",
    "destination": "AustinTxUsa"
}

###

GET {{HostAddress}}/api/freight-shipments/{{FreightInventoryId}}
accept: application/json

###

POST http://localhost:5121/api/freight-shipments/cancel
accept: */*
Content-Type: application/json

{
    "freightShipmentId": "{{FreightInventoryId}}",
    "reason": "unknown",
    "cancelledAt": "2025-07-01T01:02:03.780Z"
}

###

